package com.happycloud.android.ui.theme

import androidx.compose.ui.graphics.Color

// ---------- 浅色（石墨灰中性底 + 克制青绿强调，对比度充足） ----------
val LightPrimary = Color(0xFF0E6A5C)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB0EBD8)
val LightOnPrimaryContainer = Color(0xFF00201D)
val LightSecondary = Color(0xFF56625D)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDAE7E1)
val LightOnSecondaryContainer = Color(0xFF141F1B)
val LightTertiary = Color(0xFF5B6461)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFDFE9E5)
val LightOnTertiaryContainer = Color(0xFF181D1C)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF7F5F1)
val LightOnBackground = Color(0xFF1B1A19)
val LightSurface = Color(0xFFF7F5F1)
val LightOnSurface = Color(0xFF1B1A19)
val LightSurfaceVariant = Color(0xFFDEDBD4)
val LightOnSurfaceVariant = Color(0xFF48473D)
val LightOutline = Color(0xFF69685E)
val LightOutlineVariant = Color(0xFFBDBBB2)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFECEAE5)
val LightSurfaceContainer = Color(0xFFE6E3DE)
val LightSurfaceContainerHigh = Color(0xFFDCD9D4)
val LightSurfaceContainerHighest = Color(0xFFD3D1CB)
val LightSurfaceTint = Color(0xFF0E6A5C)

// ---------- 深色（石墨墨黑底 + 青绿提亮） ----------
val DarkPrimary = Color(0xFF8BD3C6)
val DarkOnPrimary = Color(0xFF004039)
val DarkPrimaryContainer = Color(0xFF025047)
val DarkOnPrimaryContainer = Color(0xFFAFEFDC)
val DarkSecondary = Color(0xFFBECBC5)
val DarkOnSecondary = Color(0xFF28342F)
val DarkSecondaryContainer = Color(0xFF3E4B45)
val DarkOnSecondaryContainer = Color(0xFFDAE7E1)
val DarkTertiary = Color(0xFFC2CCC8)
val DarkOnTertiary = Color(0xFF2C3431)
val DarkTertiaryContainer = Color(0xFF424C49)
val DarkOnTertiaryContainer = Color(0xFFDFE9E5)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF171513)
val DarkOnBackground = Color(0xFFE6E4DF)
val DarkSurface = Color(0xFF171513)
val DarkOnSurface = Color(0xFFE6E4DF)
val DarkSurfaceVariant = Color(0xFF3C3F3D)
val DarkOnSurfaceVariant = Color(0xFFC2C4C0)
val DarkOutline = Color(0xFF9A9C98)
val DarkOutlineVariant = Color(0xFF3B3E3B)
val DarkSurfaceContainerLowest = Color(0xFF11100F)
val DarkSurfaceContainerLow = Color(0xFF171513)
val DarkSurfaceContainer = Color(0xFF1D1B19)
val DarkSurfaceContainerHigh = Color(0xFF232221)
val DarkSurfaceContainerHighest = Color(0xFF2B2A28)
val DarkSurfaceTint = Color(0xFF8BD3C6)