package com.happycloud.android.ui.theme

import androidx.compose.ui.graphics.Color

// ---------- 浅色（暖陶土 / 琥珀，克制而不俗套） ----------
val LightPrimary = Color(0xFF8B5000)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFDCBC)
val LightOnPrimaryContainer = Color(0xFF2D1600)
val LightSecondary = Color(0xFF705A42)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFCDDBF)
val LightOnSecondaryContainer = Color(0xFF271806)
val LightTertiary = Color(0xFF5B6233)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFDFE8AD)
val LightOnTertiaryContainer = Color(0xFF181D00)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFF8F5)
val LightOnBackground = Color(0xFF221A12)
val LightSurface = Color(0xFFFFF8F5)
val LightOnSurface = Color(0xFF221A12)
val LightSurfaceVariant = Color(0xFFF3DFD0)
val LightOnSurfaceVariant = Color(0xFF52443A)
val LightOutline = Color(0xFF857468)
val LightOutlineVariant = Color(0xFFD6C3B4)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFFFF1E9)
val LightSurfaceContainer = Color(0xFFFCEBE0)
val LightSurfaceContainerHigh = Color(0xFFF6E5DA)
val LightSurfaceContainerHighest = Color(0xFFF0DFD5)
val LightSurfaceTint = Color(0xFF8B5000)

// ---------- 深色 ----------
val DarkPrimary = Color(0xFFF5B96F)
val DarkOnPrimary = Color(0xFF4A2800)
val DarkPrimaryContainer = Color(0xFF693C00)
val DarkOnPrimaryContainer = Color(0xFFFFDCBC)
val DarkSecondary = Color(0xFFDBC1A5)
val DarkOnSecondary = Color(0xFF3F2D1A)
val DarkSecondaryContainer = Color(0xFF57432E)
val DarkOnSecondaryContainer = Color(0xFFFCDDBF)
val DarkTertiary = Color(0xFFC2CC88)
val DarkOnTertiary = Color(0xFF2D3210)
val DarkTertiaryContainer = Color(0xFF43491E)
val DarkOnTertiaryContainer = Color(0xFFDFE8AD)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1A120C)
val DarkOnBackground = Color(0xFFF0E0D4)
val DarkSurface = Color(0xFF1A120C)
val DarkOnSurface = Color(0xFFF0E0D4)
val DarkSurfaceVariant = Color(0xFF52443A)
val DarkOnSurfaceVariant = Color(0xFFD6C3B4)
val DarkOutline = Color(0xFF9E8D81)
val DarkOutlineVariant = Color(0xFF52443A)
val DarkSurfaceContainerLowest = Color(0xFF140D08)
val DarkSurfaceContainerLow = Color(0xFF221A12)
val DarkSurfaceContainer = Color(0xFF271E17)
val DarkSurfaceContainerHigh = Color(0xFF32281F)
val DarkSurfaceContainerHighest = Color(0xFF3D3229)
val DarkSurfaceTint = Color(0xFFF5B96F)
